In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

Saving orders_dataset.csv to orders_dataset.csv

**Clean Order Dataset**

---

In [18]:
order_df = pd.read_csv('olist_orders_dataset.csv')
order_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [19]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [24]:
# Change Date data type

order_df['order_purchase_timestamp'] = pd.to_datetime(order_df['order_purchase_timestamp'])
order_df['order_approved_at'] = pd.to_datetime(order_df['order_approved_at'])
order_df['order_delivered_carrier_date'] = pd.to_datetime(order_df['order_delivered_carrier_date'])
order_df['order_delivered_customer_date'] = pd.to_datetime(order_df['order_delivered_customer_date'])
order_df['order_estimated_delivery_date'] = pd.to_datetime(order_df['order_estimated_delivery_date'])

order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [26]:
order_df = order_df.dropna(subset=['order_delivered_customer_date'])
order_df.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      1
order_delivered_customer_date     0
order_estimated_delivery_date     0
dtype: int64

In [29]:
# Add new column
# delivery days
order_df['delivery_days'] = (
    order_df['order_delivered_customer_date'] - order_df['order_purchase_timestamp']
).dt.days

# delivery status
order_df['delivery_status'] = order_df.apply(
    lambda x: 'Late' if x['order_delivered_customer_date'] > x['order_estimated_delivery_date'] else 'On Time',
    axis=1
)

order_df.head()

/tmp/ipykernel_5462/216973324.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  order_df['delivery_days'] = (
/tmp/ipykernel_5462/216973324.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  order_df['delivery_status'] = order_df.apply(

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8,On Time
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13,On Time
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9,On Time
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13,On Time
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2,On Time

In [32]:
order_df.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      1
order_delivered_customer_date     0
order_estimated_delivery_date     0
delivery_days                     0
delivery_status                   0
dtype: int64

In [35]:
# Better Readability - change columns name

order_df = order_df.rename(columns={
    'order_purchase_timestamp': 'order_placed',
    'order_delivered_customer_date': 'delivered_date',
    'order_estimated_delivery_date': 'expected_delivery_date',
    'order_approved_at': 'approved_time'
})

order_df.head()

,order_id,customer_id,order_status,order_placed,approved_time,order_delivered_carrier_date,delivered_date,expected_delivery_date,delivery_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8,On Time
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13,On Time
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9,On Time
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13,On Time
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2,On Time

In [37]:
# Make names: lowercase, no spaces, consistent
order_df.columns = order_df.columns.str.lower().str.strip()
order_df.head()

,order_id,customer_id,order_status,order_placed,approved_time,order_delivered_carrier_date,delivered_date,expected_delivery_date,delivery_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8,On Time
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13,On Time
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9,On Time
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13,On Time
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2,On Time

In [46]:
# Change column values in title
order_df['order_status'] = order_df['order_status'].str.title()

In [47]:
order_df['delivery_days'].describe()

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [48]:
order_df['delivered_date'].isnull().sum()

np.int64(0)

In [49]:
# Download the order dataset file
order_df.to_csv('order_df.csv', index=False)
files.download('order_df.csv')

**Order_items Dataset**

---

In [1]:
from google.colab import files
uploaded = files.upload()

ModuleNotFoundError: No module named 'google'

In [53]:
# Check nulls
order_items_df = pd.read_csv('order_items_dataset.csv')
order_items_df.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [54]:
# Check Duplicates
order_items_df.duplicated().sum()

np.int64(0)

In [55]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [56]:
# Fix data types
order_items_df['shipping_limit_date'] = pd.to_datetime(order_items_df['shipping_limit_date'])
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [57]:
# Create new Columns

order_items_df['total_value'] = order_items_df['price'] + order_items_df['freight_value']
order_items_df['total_value'].describe()

count    112650.000000
mean        140.644059
std         190.724394
min           6.080000
25%          55.220000
50%          92.320000
75%         157.937500
max        6929.310000
Name: total_value, dtype: float64

In [60]:
order_items_df[['price','freight_value','total_value']].describe()

               price  freight_value    total_value
count  112650.000000  112650.000000  112650.000000
mean      120.653739      19.990320     140.644059
std       183.633928      15.806405     190.724394
min         0.850000       0.000000       6.080000
25%        39.900000      13.080000      55.220000
50%        74.990000      16.260000      92.320000
75%       134.900000      21.150000     157.937500
max      6735.000000     409.680000    6929.310000

In [61]:
order_items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04

In [81]:
# Download the order dataset file
order_items_df.to_csv('order_items_df.csv', index=False)
files.download('order_items_df.csv')

**Order Reviews dataset**

---

In [3]:
from google.colab import files
uploaded = files.upload()

ModuleNotFoundError: No module named 'google'

In [67]:
# Check nulls
reviews_df = pd.read_csv('olist_order_reviews_dataset.csv')
reviews_df.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [69]:
# Remove the too many null columns
reviews_df = reviews_df.drop(columns=['review_comment_title','review_comment_message'])

reviews_df.head()

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01 00:00:00,2018-03-02 10:26:53

In [70]:
reviews_df.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [71]:
# check duplicates
reviews_df.duplicated().sum()

np.int64(0)

In [72]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_creation_date     99224 non-null  object
 4   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [73]:
# Fix data type
reviews_df['review_creation_date'] = pd.to_datetime(reviews_df['review_creation_date'])
reviews_df['review_answer_timestamp'] = pd.to_datetime(reviews_df['review_answer_timestamp'])
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_creation_date     99224 non-null  datetime64[ns]
 4   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 3.8+ MB

In [75]:
# Create new column

def review_category(score):
  if score >= 4:
    return 'Positive'
  elif score == 3:
    return 'Neutral'
  else:
    return 'Negative'

reviews_df['review_category'] = reviews_df['review_score'].apply(review_category)
reviews_df.head()

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp,review_category
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18 21:46:59,Positive
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10,2018-03-11 03:05:13,Positive
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17,2018-02-18 14:36:24,Positive
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21,2017-04-21 22:02:06,Positive
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01,2018-03-02 10:26:53,Positive

In [78]:
reviews_df['review_category'].value_counts()

review_category
Positive    76470
Negative    14575
Neutral      8179
Name: count, dtype: int64

In [77]:
reviews_df.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
review_category            0
dtype: int64

In [82]:
# Download the order dataset file
reviews_df.to_csv('reviews_df.csv', index=False)
files.download('reviews_df.csv')

**Customer Dataset**

---

In [4]:
from google.colab import files
uploaded = files.upload()

ModuleNotFoundError: No module named 'google'

In [83]:
customers_df = pd.read_csv('customers_dataset.csv')

# Check nulls
customers_df.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [85]:
# Check duplicates

customers_df.duplicated().sum()

np.int64(0)

In [86]:
# Fix data types

customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [88]:
# change column values format

customers_df['customer_city'] = customers_df['customer_city'].str.title().str.strip()
customers_df['customer_state'] = customers_df['customer_state'].str.upper()
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP

In [89]:
# Download the order dataset file
customers_df.to_csv('customers_df.csv', index=False)
files.download('customers_df.csv')

**Product Dataset**
---

In [90]:
from google.colab import files
uploaded = files.upload()

Saving product_category_name_translation.csv to product_category_name_translation (1).csv
Saving products_dataset.csv to products_dataset.csv

In [127]:
products_df = pd.read_csv('products_dataset.csv')

# Check nulls
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [128]:
# Remove the nulls values

products_df = products_df.dropna(subset=['product_category_name','product_weight_g',
                                         'product_length_cm', 'product_height_cm', 'product_width_cm'])
products_df.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [129]:
# Check duplicates

products_df.duplicated().sum()

np.int64(0)

In [130]:
# Drop unwanted columns

products_df = products_df.drop(columns=['product_name_lenght', 'product_description_lenght', 'product_photos_qty'])
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32340 non-null  object
 1   product_category_name  32340 non-null  object
 2   product_weight_g       32340 non-null  float64
 3   product_length_cm      32340 non-null  float64
 4   product_height_cm      32340 non-null  float64
 5   product_width_cm       32340 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.7+ MB

In [131]:
# Change product category name (in Portuguese to English)

# First load the translate table
product_category_name_translation = pd.read_csv('product_category_name_translation.csv')

products_df = products_df.merge(product_category_name_translation, on = 'product_category_name', how= 'left')

products_df.isnull().sum()

product_id                        0
product_category_name             0
product_weight_g                  0
product_length_cm                 0
product_height_cm                 0
product_width_cm                  0
product_category_name_english    13
dtype: int64

In [132]:
# After merge drop the Portuguses column

products_df = products_df.drop(columns=['product_category_name'])
products_df.head()

,product_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,625.0,20.0,17.0,13.0,housewares

In [133]:
# Rename the product category column

products_df = products_df.rename(columns={'product_category_name_english': 'product_category'})
products_df.head()

,product_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category
0,1e9e8ef04dbcff4541ed26657ea517e5,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,625.0,20.0,17.0,13.0,housewares

In [134]:
# Change the values format

products_df['product_category'] = products_df['product_category'].str.title()
products_df.head()

,product_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category
0,1e9e8ef04dbcff4541ed26657ea517e5,225.0,16.0,10.0,14.0,Perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,1000.0,30.0,18.0,20.0,Art
2,96bd76ec8810374ed1b65e291975717f,154.0,18.0,9.0,15.0,Sports_Leisure
3,cef67bcfe19066a932b7673e239eb23d,371.0,26.0,4.0,26.0,Baby
4,9dc1a7de274444849c219cff195d0b71,625.0,20.0,17.0,13.0,Housewares

In [135]:
# Replace the underscore in category value

products_df['product_category'] = products_df['product_category'].str.replace('_', " ")
products_df.head()

,product_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category
0,1e9e8ef04dbcff4541ed26657ea517e5,225.0,16.0,10.0,14.0,Perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,1000.0,30.0,18.0,20.0,Art
2,96bd76ec8810374ed1b65e291975717f,154.0,18.0,9.0,15.0,Sports Leisure
3,cef67bcfe19066a932b7673e239eb23d,371.0,26.0,4.0,26.0,Baby
4,9dc1a7de274444849c219cff195d0b71,625.0,20.0,17.0,13.0,Housewares

In [136]:
products_df['product_category'].value_counts()

product_category
Bed Bath Table               3029
Sports Leisure               2867
Furniture Decor              2657
Health Beauty                2444
Housewares                   2335
                             ...
Tablets Printing Image          9
Fashion Childrens Clothes       5
Home Comfort 2                  5
Security And Services           2
Cds Dvds Musicals               1
Name: count, Length: 71, dtype: int64

In [138]:
# Rearrange the columns order

products_df = products_df[
     [
        'product_id',
        'product_category',
        'product_weight_g',
        'product_length_cm',
        'product_height_cm',
        'product_width_cm'
    ]
]

products_df.head()

,product_id,product_category,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,Sports Leisure,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,Baby,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,Housewares,625.0,20.0,17.0,13.0

In [139]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32340 entries, 0 to 32339
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         32340 non-null  object
 1   product_category   32327 non-null  object
 2   product_weight_g   32340 non-null  float64
 3   product_length_cm  32340 non-null  float64
 4   product_height_cm  32340 non-null  float64
 5   product_width_cm   32340 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.5+ MB

In [140]:
# Download the order dataset file
products_df.to_csv('products_df.csv', index=False)
files.download('products_df.csv')

**Payments Dataset**
---

In [141]:
from google.colab import files
uploaded = files.upload()

Saving order_payments_dataset.csv to order_payments_dataset.csv

In [142]:
payments_df = pd.read_csv('order_payments_dataset.csv')
payments_df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [143]:
# check null
payments_df.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [144]:
# Check Duplicates

payments_df.duplicated().sum()

np.int64(0)

In [145]:
payments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [147]:
# Column value format change

payments_df['payment_type'] = payments_df['payment_type'].str.title().str.strip().str.replace("_", " ")
payments_df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,Credit Card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,Credit Card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,Credit Card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,Credit Card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,Credit Card,2,128.45

In [148]:
# Revenue check column

payments_df['payment_value'].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [149]:
# Download the order dataset file
payments_df.to_csv('payments_df.csv', index=False)
files.download('payments_df.csv')

**Seller dataset**

---

In [150]:
from google.colab import files
uploaded = files.upload()

Saving sellers_dataset.csv to sellers_dataset.csv

In [151]:
seller_df = pd.read_csv('sellers_dataset.csv')

# Check null
seller_df.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [152]:
# Check duplicates

seller_df.duplicated().sum()

np.int64(0)

In [158]:
# Standardize text

seller_df['seller_city'] = seller_df['seller_city'].str.title().str.strip()
seller_df['seller_state'] = seller_df['seller_state'].str.upper()

In [159]:
# Download the order dataset file
seller_df.to_csv('seller_df.csv', index=False)
files.download('seller_df.csv')

**Geolocation dataset**

---

In [160]:
from google.colab import files
uploaded = files.upload()

Saving geolocation_dataset.csv to geolocation_dataset.csv

In [162]:
geolocation_df = pd.read_csv('olist_geolocation_dataset.csv')
geolocation_df.head()

# Check null

geolocation_df.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [163]:
# Check duplicate

geolocation_df.duplicated().sum()

np.int64(261831)

In [164]:
# Standardize text

geolocation_df['geolocation_city'] = geolocation_df['geolocation_city'].str.title().str.strip()
geolocation_df['geolocation_state'] = geolocation_df['geolocation_state'].str.upper()

In [165]:
# Download the order dataset file
geolocation_df.to_csv('geolocation_df.csv', index=False)
files.download('geolocation_df.csv')